---
global:
  scrape_interval: 5m
  scrape_timeout: 2m

scrape_configs:
# iperf3 tests
  - job_name: 'iperf3-probe'
    metrics_path: /probe
    static_configs:
      - targets:
        - targets/iperf3-server.yml
    params:
      port: ['5201']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.16:9579

  - job_name: 'iperf3-probe-2'
    metrics_path: /probe
    static_configs:
      - targets:
        - targets/iperf3-client.yml
    params:
      port: ['5201']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.13:9579
# speedtest tests
  - job_name: 'speedtest-probe-1'
    metrics_path: /probe
    static_configs:
    - targets:
      - targets/speedtest1.yml
  - job_name: 'speedtest-probe-2'
    metrics_path: /probe
    static_configs:
    - targets:
      - targets/speedtest2.yml
# blackbox tests
  - job_name: 'blackbox-probe-http-1'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - targets/http.yaml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.13:9116
  - job_name: 'blackbox-probe-icmp-1'
    metrics_path: /probe
    params:
      module: [icmp_test]
    file_sd_configs:
      - files:
        - targets/icmp.yaml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.13:9116
  - job_name: 'blackbox-probe-dns-1'
    metrics_path: /probe
    params:
      module: [dns_test]
    file_sd_configs:
      - files:
        - targets/dns.yaml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.13:9117
  - job_name: 'blackbox-probe-http-parser-1'
    metrics_path: /probe
    params:
      module: [http_parsing]
    file_sd_configs:
      - files:
        - targets/http.yaml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.125.30.13:9118